### PR TITLE
Improved performance of resample thread

### PR DESCRIPTION
**Pull request by philipstarkey**
While the resapmle algorithm released the GIL, we did not take advantage of the fact that this meant we could resample multiple channels in parallel.
A ThreadPool is now created to resample channels in parallel.
The code was also optimised to remove logging lines and reduce the number of calls in `inmain`, thus limiting the contention with pyqtgraph redraws and mouse move events.

### CODE REVIEW

**Comment by philipstarkey** [comment]
pyqtgraph still seems to have poor performance when zoomed out on pseudoclock traces. I'm not sure why this is. Performance is significantly better when zoomed in enough that you start to be able to resolve individual clock ticks. Either way, resampling is happening much faster with this PR. It's particularly noticable if you zoom into a pseudoclock trace and then scroll left and right. Data loads much faster than previously!

**Comment by philipstarkey** [comment]
Will merge on Monday if no comments

**Comment by dihm** [comment]
@philipstarkey Can I safely assume this can be merged? If so, I'll go ahead and take care of it.

**Comment by dihm** [comment]
Fair enough. I've confirmed that runviewer still works with this commit, so I'm going to merge.

**Pull request merged**
